---
title: "issue-30"
date: 2026-04-28
---

### Proveedor de la información

Luis Montilla

### Datos de contacto

repo-tree@proton.me

### Apellido(s) del tesista

Pérez García

### Nombre(s) del tesista

Belkys Yubiry

### ORCID del estudiante

0000-0002-4335-4496

### Título de la tesis

Estructura de la comunidad de macroinvertebrados bentónicos en distintos tipos de arreglos hidrogeomorfológicos del cauce

### Resumen

La regulación de la estructura de las comunidades de macroinvertebrados bentónicos en función de las características hidráulicas y geomorfológicas que definen al tramo y a las unidades del cauce o hábitats, ha sido ampliamente estudiada en las regiones templadas y en menor medida en la región neotropical. Sin embargo, en la mayoría de estas investigaciones la descripción física de los tramos se ha simplificado mucho o se ha basado en una caracterización muy superficial de los mismos. Puesto que la organización espacial de la comunidad de macroinvertebrados acuáticos depende de las propiedades hidraúlicas y morfológicas del cauce el cual da soporte a los diferentes tipos de microambientes donde se establece este tipo de fauna, en esta investigación queremos intentar probar que la estructura de las comunidades de macroinvertebrados bentónicos responde al arreglo físico del cauce y a las condiciones hidráulicas. De ser cierta esta premisa los diferentes ensamblajes de la comunidad de macroinvertebrados acuáticos deberían mostrar patrones espaciales y temporales en su organización estrechamente relacionados con la variación de las propiedades hidrogeomorfológica de los tramos. Con el propósito de verificar la hipótesis planteada se caracterizó el patrón espacial y temporal de la estructura de algunos ensamblajes de comunidades de macroinvertebrados bentónicos para diferentes tipos de tramos y hábitats identificados en la microcuenca del río Guáquira. Para el logro del objetivo se utilizó la clasificación de los tramos que conforman el cauce de los ríos propuesta por Montgomery & Buffington (1997) y la clasificación de las unidades del cauce o hábitats que conforma el lecho de los ambientes fluviales propuesta por Hawkins et al. (1993). Basados en los dos esquemas de clasificación antes señalados, se identificaron cuatro tipos de tramos: Rápidos-Remansos (RR), Lecho-Plano (LP), Escalón-Remanso (ER) y Cascada (C). Los dos primeros se ubicaron en el río Guáquira (3er. orden) y los dos últimos en el río la Herrera (1er. orden), tributario del primero. Se llevaron a cabo siete campañas de muestreo que abarcaron los períodos de sequía (enero y marzo 2012), lluvias (mayo, julio, agosto 2012) y fin de lluvias (diciembre 2011 y noviembre 2012). En cada campaña se colectó, dentro de cada tramo la fauna bentónica con una red Surber (tamaño de poro: 300µm, área: 0,0961m2) a nivel de los hábitats de remansos (Re), correderas (Co) y rápidos (Ra), y se midieron las variables morfométricas que describieron la hidráulica del tramo y del hábitat (velocidad de la corriente, profundidad, ancho y caudal); las variables de composición del sustrato tanto inorgánico (arena, grava, guijarros, cantos) como orgánico (materia orgánica particulada fina y gruesa) y las variables fisicoquímicas del agua (oxígeno disuelto, temperatura, pH, conductividad, turbidez, nítritos, nítratos y sulfatos). Los macroinvertebrados se identificaron hasta la menor resolución taxonómica, haciendo énfasis en los Órdenes Ephemeroptera, Trichoptera, Plecoptera y Coleoptera por ser los grupos mejor estudiados en el Neotrópico. Se estimaron atributos biológicos tales como la riqueza, la densidad, la equitatividad y la diversidad, se cuantificó la densidad total por comunidad de macroinvertebrados, efemerópteros y tricópteros y la densidad para ciertos taxa- específicos. La composición taxonómica y de grupos funcionales se comparó a escala del tramo y del hábitat, mediante los métodos multivariados de Escalamiento Multidimensional no Métrico (EMNM), Análisis de Similitud (ANOSIM) y Porcentaje de Similitud (SIMPER). La evaluación de las características hidrogeomorfológicas de los tramos arrojó los siguientes resultados: las conformaciones Rápidos- Remansos y Lecho-Plano del río Guáquira fueron más disimiles entre sí, que las de Escalón-Remanso y Cascada del río Herrera. Las variables que diferenciaron a los tramos estuvieron principalmente relacionadas a la hidráulica y al arreglo y heterogeneidad del sustrato; aunque la conductividad también fue clave en la discriminación. En cuanto a las unidades del cauce, fue posible reconocer cada tipo de hábitat como parches cuasidiscretos que se diferenciaron tanto por la velocidad de la corriente como por la acumulación de materia orgánica fina. La estructura de la comunidad de macroinvertebrados bentónicos, y de los ensamblajes de efemerópteros y tricópteros, a la escala del tramo, difirió como una función de las características hidrogeomorfológicas que definieron al cauce de ambos cuerpos de agua. La composición taxonómica de las comunidades de macroinvertebrados tendió a diferir entre tramos, siendo mayor la diferencia entre los más alejados en el gradiente longitudinal, es decir, entre Rápidos-Remansos y Cascada. Las variables abióticas que se relacionaron con la distribución espacial de la composición taxonómica fueron principalmente las hidráulicas: caudal, velocidad, ancho y profundidad, junto con la conductividad. Los atributos riqueza, densidad y diversidad también evidenciaron diferencias entre algunos tramos. En este sentido la densidad difirió entre ríos más que entre tramos y en la escala temporal sus valores disminuyeron en la época de lluvias. La distribución porcentual de los grupos funcionales pareció ajustarse a la teoría del continuo del río propuesta por Vannote et al. (1980). En este sentido, los fragmentadores fueron más abundantes en los tramos del río Herrera, y los recolectores y raspadores fueron más abundantes en el río Guáquira, en tanto que los depredadores mostraron pocas variaciones entre ambos ríos. A escala de los hábitats se observaron variaciones en los atributos biológicos, pero estas no fueron consistentes a lo largo de los tramos; en el caso de la composición taxonómica, esta siempre fue diferente entre remansos y rápidos al interior de los cuatro tipos de tramos seleccionados, mientras que las correderas exhibieron una composición intermedia, siendo claves las variables hidráulicas y de composición del sustrato en la distribución espacial de los macroinvertebrados bentónicos. En cuanto a otros atributos, se evidenció que la diversidad fue la única en diferir entre hábitats dentro de la mayoría de los tramos, y tendió a ser significativamente alta en correderas y rápidos. El tramo Cascada fue el único en exhibir diferencias entre hábitats para la mayoría de los atributos, siendo la densidad, la riqueza y la diversidad significativamente altas en los rápidos. Al evaluar las densidades taxa-específica entre hábitats se identificaron por un lado, un mayor número de taxa con preferencias por los rápidos, tales como los géneros Baetodes, Thraulodes, Leptonema, Smicridea, Chimarra, Anacroneuria, Simulium, Macrelmis, Austrolimnius y Anchitarsus, la subfamilia Orthocladiinae, entre otros; por otro lado, un menor número de taxa exclusivos de los remansos, tales como los géneros Trichorythodes, Farrodes, Polyplectropus, y la subfamilia Tanypodinae entre otros; y finalmente un grupo de taxa sin preferencia por algún hábitat, tales como los géneros Xyphocentron, Marilia, Helicopsyche, las subfamilias Chironomiinae y Tanytarsiini, la familia Ceratopogonidae y la clase Hydracarina, entre otros. En cuanto a la composición de grupos funcionales, las diferencias entre hábitats solo fueron observables en los tramos del río la Herrera. Así tenemos que, en el tramo Escalón-Remanso su distribución pareció seguir los supuestos del modelo del continuo del río de forma que en los hábitats de este tramo dominaron los recolectores-ramoneadores seguidos de fragmentadores, raspadores, depredadores y recolectores-filtradores. Aun cuando en el río Guáquira no se observaron diferencias significativas en la densidad de grupos funcionales entre hábitats, no obtstante, los raspadores tendieron a dominar en los hábitats de los tramos Rápidos-Remansos y Lecho-Plano, seguidos de los recolectores- ramoneadores, depredadores, recolectores-filtradores y fragmentadores. Los recolectores-ramoneadores fueron el único grupo funcional que abundó en Remansos, mientras que los restantes tendieron a ser abundantes en correderas y rápidos. Este estudio evidenció la importancia de la hidrogeomorfología, sobre la organización de las comunidades bentónicas tanto a escala del tramo como de las unidades del cauce. Los procesos hidrogeomorfológicos afectan el transporte y deposición de la materia orgánica, la organización espacial de los diferentes tamaños del sustrato inorgánico, además de los gradientes de velocidad y profundidad que se expresan en los diferentes tipos de hábitats que conforman el lecho; de tal manera que, la organización de las comunidades responde tanto a las variables abióticas locales como a los procesos hidrogeomorfológicos que operan a mayor escala.

### Mes

12

### Año

2015

### Universidad

Universidad Central de Venezuela

### Título obtenido

Doctorado

### Apellidos de quien tutoreó la tesis

Segnini Flores

### Nombre de quien tutoreó la tesis

Samuel Enrique

### ORCID del Tutor

0000-0002-3936-5766

### Afiliación de quien tutoreó la tesis

Universidad de Los Andes

### Apellidos de quien cotutoreó la tesis

_No response_

### Nombre de quien cotutoreó la tesis

_No response_

### ORCID del segundo Tutor

_No response_

### Afiliación de quien cotutoreó la tesis

None

### Palabras clave

_No response_

### Confirmación de documentos

- [x] Confirmo que la información provista es legítima
