---
title: "issue-12"
date: 2025-12-05
---

### Proveedor de la información

Ana Melisa Fernandes, UCV.

### Datos de contacto

fernandesanameli@gmail.com

### ApellidoAutor

Fernandes

### NombreAutor

Ana Melisa

### ORCID del estudiante

0000-0003-3944-4795

### Título de la tesis

Relaciones de dominancia interespecífica en colibríes (Aves, Trochilidae) asociados a comederos artificiales

### Resumen

Los colibríes (Trochilidae) pertenecen a una familia de aves muy diversa y abundante en el Neotrópico y se caracterizan por presentar conductas agresivas con otras especies por el uso de alimento. Aunque muchos estudios han descrito la conducta de los colibríes en la naturaleza alrededor de árboles y/o arbustos en flor, pocos estudios han utilizado comederos artificiales para el estudio de patrones de dominancia entre especies. Adicionalmente, pocos han analizado el efecto de la variación espacio-temporal en composición de especies sobre estas relaciones de dominancia. Los ensambles de colibríes en estas localidades varían en su riqueza de especies, tanto espacial como temporalmente, permitiendo comparar las relaciones de dominancia entre las especies, así como su variabilidad espacial y temporal. El objetivo de este estudio fue describir las relaciones de dominancia entre varias especies de colibríes, las cuales utilizan un recurso común (comederos artificiales), en tres localidades de estudio durante los meses de febrero y mayo. Se registraron las interacciones agresivas en los comederos (suplantación, persecución y pelea) definiendo como ganador al que inicia la interacción y logra suplantar al otro individuo y quedarse con el recurso. Los patrones observados se compararon con base en índices de dominancia (DS y I&IS), linealidad (h’), transitividad (Ttri), así como el uso de redes de interacción. También se evaluó el potencial efecto del peso corporal de las especies en la posición jerárquica. Colibri coruscans y C. delphinae fueron las especies más dominantes para las tres localidades en los dos meses, mientras que Amazilia tobaci y Chrysuronia oenone fueron las especies subordinadas. Las comunidades de colibríes estudiadas no siguen una jerarquía de dominancia lineal. Sin embargo, la dominancia de las especies estuvo relacionada con el peso corporal, en el que las especies de mayor peso corporal dominaron sobre las pequeñas.

### Mes

2

### Año

2018

### Universidad

Universidad Central de Venezuela

### Departamento

Departamento de Ciencias, escuela de Biología.

### Título obtenido

Licenciatura

### Apellidos de quien tutoreó la tesis

Pérez-Emán

### Nombre de quien tutoreó la tesis

Jorge

### ORCID del Tutor

0000-0002-9155-1275

### Apellidos de quien cotutoreó la tesis

Griffon

### Nombre de quien cotutoreó la tesis

Diego

### ORCID del segundo Tutor

0000-0003-1296-9145

### Palabras clave

Dominancia, jerarquías de dominancia, Trochilidae, comederos artificiales.

### Licencia

CC BY

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
