---
title: "issue-1"
date: 2025-08-17
---

### Proveedor de la información

Carlos Brett

### Datos de contacto

cajabrett@gmail.com

### Autor(es)

Carlos Javier Brett Sanchez

### ORCID del autor de la tesis

0000-0002-1833-5082

### Título de la tesis

COMPOSICIÓN DE LA DIETA DE Pterois volitans EN CHICHIRIVICHE DE LA  COSTA, EDO. VARGAS (VENEZUELA).

### Resumen/Abstract

Pterois volitans (pez león) es una especie invasora que ha sido introducida desde el océano Indo-Pacífico al Atlántico occidental. En el año 2009 fue reportado en las costas venezolanas y debido a sus características bio-ecológicas, luce necesario evaluar las posibles repercusiones que pueda tener sobre la fauna de peces e invertebrados de las localidades invadidas, dado que ha sido señalado como un depredador de apetito voraz. Durante el presente estudio se describió, a través de análisis de contenidos estomacales, la dieta de 216 ejemplares de P. volitans capturados durante el período Diciembre2010-Mayo2011, en la localidad de Chichiriviche de la Costa, Edo. Vargas. En función de algunas variables utilizadas para evaluar la dieta de los peces (índice de repleción, frecuencia numérica y de aparición, porcentaje gravimétrico y de cobertura) se calculó un índice compuesto de importancia relativa (IIR) para determinar la relevancia ponderada de cada renglón alimentario. Se caracterizó la dieta, determinando que la misma se compone de crustáceos y peces de pequeño tamaño, abarcando hasta 19 familias de peces y 7 grupos de crustáceos. La dieta varía en función de la talla, de manera que la de los ejemplares pequeños resultó menos variada y tiene a los camarones como componente principal, mientras que los ejemplares más grandes incluyen un mayor número de renglones incorporando familias de peces que alcanzan mayores tallas.

### Mes de publicación

Octubre

### Año

2012

### Universidad

Universidad Simón Bolívar

### Departamento

Coordinación de Biología

### Título obtenido

Licenciatura

### Tutor

Juan Posada

### ORCID del Tutor

_No response_

### Tutor adicional

Eduardo Klein

### ORCID del segundo Tutor

0000-0003-2935-7065

### Palabras clave

contenidos estomacales, especies invasoras, pez león, Pterois volitans, índice de importancia, hábitos alimenticios, dieta, impacto ecológico

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
