---
title: "issue-16"
date: 2025-12-16
---

### Proveedor de la información

Jose F. Grillo, USB

### Datos de contacto

josefgrilloc@gmail.com

### ApellidoAutor

Grillo Cañizales

### NombreAutor

José Francisco

### ORCID del estudiante

0000-0002-7496-3622

### Título de la tesis

Interacción entre micropartículas de Poliestireno y el coral Porites porites: Posibles efectos tóxicos

### Resumen

Los microplásticos (MP), fragmentos cuyo diámetro es menor a 5 mm, han surgido como un contaminante de alta preocupación en ambientes marinos. Organismos bentónicos, como los corales, presentan alto riesgo de sufrir efectos tóxicos por exposición a MP. Este trabajo buscó estudiar la incorporación y efectos de la exposición con micropartículas de poliestireno (mPS) sobre la especie de coral esclaractineo Porites porites. Las mPS fueron sintetizadas mediante el método de emulsión simple/evaporación de solvente y poseían un diámetro promedio < 5 μm. Se realizó un bioensayo de toxicidad aguda de 96 horas con 4 concentraciones de mPS (1; 10; 100 y 1000 mg/L) y un control. No se registró mortalidad de los corales durante el bioensayo. Mediante técnicas histológicas se evidenció la incorporación de mPS dentro de la cavidad gastrovascular en todos los tratamientos. Se observó una tendencia a aumentar el número de partículas incorporadas conforme aumentó la concentración de mPS en el medio. Adicionalmente, en el tratamiento de mayor concentración (1000 mg/L) se observó la presencia de cúmulos de mPS dentro del tejido. No se encontraron diferencias significativas entre el control experimental y los tratamientos con respecto a la medición de biomarcadores de estrés actividad enzimática de catalasa y contenido de melanina (PERMANOVA basados en distancias euclídeas). En conclusión, el coral P. porites fue capaz de incorporar las mPS y no presentó efectos tóxicos aparentes al ser expuesto a mPS por 96 horas. Se recomienda estudiar los efectos y posibles mecanismos de la incorporación de MP a largo plazo.

### Mes

11

### Año

2019

### Universidad

Universidad Simón Bolívar

### Departamento

Departamento de Biología de Organismos

### Título obtenido

Licenciatura

### Apellidos de quien tutoreó la tesis

Ramos

### Nombre de quien tutoreó la tesis

Ruth

### ORCID del Tutor

0000-0002-9439-0657

### Apellidos de quien cotutoreó la tesis

NA

### Nombre de quien cotutoreó la tesis

_No response_

### ORCID del segundo Tutor

_No response_

### Palabras clave

Microplásticos, Poliestireno, Coral, Porites porites, Histología

### Licencia

CC BY

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
