---
title: "issue-14"
date: 2025-12-10
---

### Proveedor de la información

Irina Formoso

### Datos de contacto

irinaformoso@gmail.com

### ApellidoAutor

Formoso Caamaño

### NombreAutor

Irina

### ORCID del estudiante

_No response_

### Título de la tesis

Evaluación de paternidad múltiple en chigüires (Hydrochoerus hydrochaeris) en los llanos venezolanos.

### Resumen

La paternidad múltiple ocurre cuando en una misma camada existen crías provenientes de más de un padre, lo cual implica que la hembra copuló con más de un macho en un mismo período fértil. La paternidad múltiple tiende a ocurrir cuando existe abundancia de recursos y es más frecuente en animales que viven en grupos de ambos sexos y con un sistema de apareamiento poligínico, siendo este el caso de los chigüires (Hydrochoerus hydrochaeris) venezolanos. Este fenómeno puede tener repercusiones genéticas sobre la población, alterando el tamaño efectivo de la misma y la distribución de los alelos en ella. El chigüire, roedor de interés comercial en los llanos de Venezuela, vive en grupos y posee aspectos en su comportamiento y anatomía que sugieren un alto grado de monopolización de los apareamientos por parte del macho dominante. Por otro lado, se han observado apareamientos con más de un macho por parte de una hembra en menos de 24 horas. Estas observaciones algo contradictorias dieron pie al presente estudio, que intenta dilucidar la posibilidad de paternidad múltiple como indicador del grado de poliginia en grupos de chigüires. Utilizando material proveniente de la matanza anual de chigüires del Hato El Cedral (Edo. Apure), se colectaron muestras de tejido de hembras preñadas y de sus fetos que fueron accidentalmente sacrificadas durante la matanza. El análisis de paternidad fue realizado utilizando cinco loci de microsatélites polimórficos como marcadores moleculares. No se observó ningún caso concluyente de paternidad múltiple en la muestra, más se sospecha de su presencia en tres de las familias evaluadas.

### Mes

7

### Año

2016

### Universidad

Universidad Simón Bolívar

### Departamento

Coordinacion de Biologia

### Título obtenido

Licenciatura

### Apellidos de quien tutoreó la tesis

Herrera

### Nombre de quien tutoreó la tesis

Emilio

### ORCID del Tutor

_No response_

### Apellidos de quien cotutoreó la tesis

Santana

### Nombre de quien cotutoreó la tesis

Maria Angelica

### ORCID del segundo Tutor

_No response_

### Palabras clave

_No response_

### Licencia

CC BY

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
