---
title: "issue-3"
date: 2025-08-09
---

### Proveedor de la información

Alfredo Ascanio, USB

### Datos de contacto

ascanio.alfredoa@gmail.com

### Autor(es)

Ascanio Moreno, Alfredo Alejandro

### ORCID del autor de la tesis

0000-0001-9987-7977

### Título de la tesis

DIETA Y TRAMA TRÓFICA DE LA ICTIOFAUNA DEMERSAL EN LA ZONA MARINO-ESTUARINA ASOCIADA AL DELTA DEL ORINOCO

### Resumen/Abstract

Los peces demersales son de gran importancia económica para el oriente de Venezuela, en especial para poblados cuyo sustento depende la pesca en el área marino-estuarina asociada al delta del río Orinoco. A pesar de la importancia ecológica y económica de esta área geográfica, la estructura trófica de la comunidad de peces demersales de esta región es poco conocida. En el presente estudio se evaluó la estructura tal comunidad de peces, sus dietas y tramas tróficas, considerando tres localidades con características ambientales diferentes, dentro del área marino-estuarina del delta del río Orinoco: (1) Golfo de Paria, (2) Boca de Serpiente y (3) Boca Grande. Para ello, se realizaron muestreos entre abril y mayo de 2015, utilizando pesca de arrastre. Esto permitió analizar 315 estómagos correspondientes a 29 especies de peces. Los datos fueron utilizados para estimar la variación espacial en la estructura de la comunidad y en las características de las tramas tróficas entre y dentro de localidades (i.e., estaciones), utilizando el índice de Bray-Curtis como métrica de similitud, un índice de importancia relativa (IIR) como medida de la importancia de las presas en la dieta y análisis de redes complejas, respectivamente. Los resultados mostraron que existen variaciones espaciales a escala de localidades y estaciones en la composición de la dieta de especies como el roncador (Micropogonias furnieri), la paguara (Chaetodipterus faber), y las curvinas Cynoscion virescens y Cynoscion similis. Esto se debió tanto a variaciones en el tipo de ítems consumidos y a cambios en su importancia relativa por especie y localidad. Se determinó que los Crustáceos y Peces son los ítems alimenticios que brindan mayor estabilidad a las redes tróficas, junto a la especie Micropogonias furnieri. Esto parece indicar que la desaparición de alguno de estos ítems puede traer como consecuencia la desaparición de otras especies. Por su parte, otros Ítems como Detrito y Moluscos fueron relevantes en la trama trófica de Golfo de Paria. Estos resultados son de utilidad para el desarrollo de planes de explotación pesquera y de conservación de la región en el futuro, dado que ofrecen una línea base para el estudio de elementos claves en las tramas tróficas de especies de interés comercial en la zona marino-estuarina asociada al delta del Orinoco y cómo éstas responderían a potenciales disturbios humanos.

### Mes de publicación

Enero

### Año

201i

### Universidad

Universidad Simón Bolívar

### Departamento

Departamento de Estudios Ambientales

### Título obtenido

Licenciatura

### Tutor

Cróquer, Aldo

### ORCID del Tutor

0000-0001-8880-9338

### Tutor adicional

_No response_

### ORCID del segundo Tutor

_No response_

### Palabras clave

Peces Demersales, Estructura Comunitaria, Composición de Dieta, Tramas Tróficas, Estuario, Delta del Río Orinoco

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
