---
title: "issue-9"
date: 2025-12-10
---

### Proveedor de la información

Beatriz Lopez Sánchez

### Datos de contacto

bealopezsanchez@gmail.com

### ApellidoAutor

López Sánchez

### NombreAutor

Beatriz Cecilia

### ORCID del estudiante

0000-0003-3250-1953

### Título de la tesis

ECOLOGÍA TRÓFICA Y ENERGÉTICA DEL CANGREJO DE MANGLE Aratus pisonii (CRUSTACEA: BRACHYURA: GRAPSIDAE) (H. MILNE EDWARDS)

### Resumen

Aratus pisonii (H. Milne Edwards, 1837) is one of the most common crustaceans in American mangroves. Certain features of their life history and population dynamics, such as size and percentage of mature females have been correlated with the structural development of mangroves. In particular, it has been documented that the size of crabs increases progressively from less developed mangroves located in hypersaline lagoons, to a maximum in mangroves at the mouths of rivers with greater structural development. The aim of this study was to investigate whether a structural gradient of mangroves leads to a variation in energetic condition and food resources used and assimilated by A. pisonii and also to assess possible variations between periods of drought and rain. The results show that the quality of the body reserves varied along the structural gradient of mangroves, suggesting the consumption of resources with diverging nutritional quality. There was an increase in the level of body reserves in hypersaline habitats with lower structural development during the dry season. The variables that described the structure of mangroves (basal area, height of mangroves) were more important than the nutritional characteristics of the leaves (Nfoliar, polyphenols), in explaining the variation in the level and quality of body reserves and gonads of this crab along the mangrove gradient. The crabs in the estuarine mangrove, the habitat with the highest structural development within the gradient evaluated, exhibited low levels of body reserves. The body stores as expressed by the C / N of the hepatopancreas, showed an increase to the habitats with higher salinity and lower structural development. The same trend was observed in nitrogen levels in skeletal muscle. Have been reported the largest body sizes of these crabs in the mangrove estuary, as well as the maximum percentage of mature females and a continuous and balanced reproduction throughout the year. It is proposed that estuarine mangrove crabs are constantly compensating for the metabolic requirements, without having to store body reserves, therefore, are directing energy to both, growth and reproduction throughout the year. The results of the analysis of stomach contents showed that in the mangrove estuary was high availability of resources in both seasons of the year, suggesting that these crabs have enough resource, which coincides with a lower storage of body reserves. The body condition of crabs decreased to less structural development mangrove with hypersaline condition, in line with a foliar resource of lower quality in these environments. Populations of A. pisonii of hypersaline environments with lower structural development seem to rely heavily on stored reserves during the drought, to achieve reproductive success in the rainy season. The storage of body reserves would be necessary for crabs in these habitats with seasonal reproduction, gather the necessary energy and achieve reproductive success. It was shown that populations of crabs that inhabit the mangroves of lower structural development (stunted) and hyper salinity conditions are limited by the resource. A trade-off was observed between the energy directed to growth and reproduction in stunted mangrove. This was confirmed by the inverse relationship observed between the energy directed to growth and reproduction. Cannibalistic behavior occurred with greater intensity in these crabs, supports the limitation of resources of these populations. In addition, these crabs have the lowest nitrogen content of muscle and lower body sizes. Stable isotope analysis showed that with decreasing the structural development of the mangroves and increasing salinity, the crabs exhibited a greater assimilation of the fraction of C and N from insects. It is likely that the crab body condition influencing the selection of the resource, especially during the drought in the hypersaline mangrove scrub, where cannibalism was detected. This behavior may be a consequence of the low quality of available resources in that habitat. Trophic relationships of A. pisonii change along the structural gradient of mangroves. In crabs living in more structural development mangrove was observed a greater assimilation of C and N of leaves. However towards the mangroves with intermediate structural development, Aratus populations behave as generalists, meaning that treated more equitably funding sources. These results contribute to a better understanding of the relationship “mangrove – crab” and extensive knowledge of the ecology of this species in the Americans mangrove.


Aratus pisonii (H. Milne Edwards, 1837) es uno de los crustáceos más frecuentes en los manglares americanos. Ciertas características de su historia de vida y dinámica poblacional, tales como, la talla y el porcentaje de hembras ovadas, han sido correlacionadas con el desarrollo estructural de los manglares; en particular, se ha documentado que la talla de los cangrejos se incrementa progresivamente desde los manglares con menor desarrollo estructural ubicados en lagunas hipersalinas, hasta una talla máxima encontrada en manglares localizados en la desembocadura de ríos con un mayor desarrollo estructural. El objetivo de este trabajo fue investigar si el gradiente estructural de manglares conlleva a una variación en la condición energética y en los recursos alimenticios empleados y asimilados por A. pisonii y evaluar las posibles variaciones entre los periodos de sequía y lluvias. Los resultados evidencian que la calidad de las reservas corporales varía a lo largo del gradiente estructural de manglares, lo que sugiere el consumo de recursos con distinta calidad nutricional. Se registra un incremento en el nivel de reservas corporales hacia los hábitats hipersalinos con menor desarrollo estructural, durante la temporada seca. Las variables que describen el gradiente de estructura de manglares parecen ser más importantes que las características nutricionales de las hojas (Nfoliar, polifenoles), en explicar la variación en el nivel y la calidad de las reservas corporales y de las gónadas a lo largo del gradiente. Los menores niveles de reservas, pero de mayor calidad, junto con altos niveles de nitrógeno en el músculo se documentaron en los cangrejos del manglar estuarino de mayor desarrollo estructural, donde se han registrado en estudios previos las mayores tallas corporales, los máximos porcentajes de hembras ovadas y reproducción continua y equilibrada a lo largo del año. Esto sugiere que los cangrejos en este hábitat están compensando continuamente los requerimientos metabólicos, sin necesidad de almacenar reservas corporales y por lo tanto, pueden dirigir energía tanto al crecimiento como a la reproducción. Los resultados del análisis de contenido estomacal evidenciaron que en el manglar estuarino hubo una alta disponibilidad de recursos en ambas temporadas del año. Las reservas corporales de los cangrejos disminuyeron su calidad hacia los manglares hipersalinos con menor desarrollo estructural, en consonancia con un recurso foliar de menor calidad en estos ambientes. Las poblaciones de A. pisonii de los ambientes hipersalinos con menor desarrollo estructural parecen depender en gran medida de las reservas almacenadas durante la sequía, para lograr el éxito reproductivo en el periodo de lluvias. Esta etapa de almacenamiento podría ser necesaria para que los cangrejos de estos hábitats con reproducción estacional, reúnan la energía suficiente y alcancen el éxito reproductivo. Se demostró que las poblaciones de cangrejos en el extremo del gradiente de salinidad y menor desarrollo estructural (achaparrado-hipersalino) están limitadas por el recurso, ya que se observó un compromiso (relación inversa) entre la energía dirigida a crecimiento y a reproducción. Esto podría explicar el canibalismo, los menores niveles de nitrógeno muscular y las menores tallas alcanzadas por los cangrejos en este hábitat. Los análisis de isótopos estables evidenciaron que a medida que disminuye el desarrollo estructural del manglar e incrementa la salinidad del agua, los cangrejos exhiben una mayor asimilación de la fracción del C y N de los insectos. Es probable que el estado nutricional del cangrejo esté influenciando la selección del recurso, sobre todo durante la sequía, particularmente en TAC donde se detectó canibalismo (consumo de huevos y apéndices de sus congéneres), la cual puede ser una consecuencia de la baja calidad de los recursos disponibles en ese hábitat. Se demostró que las relaciones tróficas de A. pisonii cambian a lo largo del gradiente de manglares estudiados. Se evidencia una mayor dependencia de las hojas del manglar en los cangrejos que habitan en manglares con mayor desarrollo estructural (consumidor de primer orden). Mientras que hacia los manglares con desarrollo estructural intermedio o bajo, y condiciones de hipersalinidad, las poblaciones de Aratus se comportan más como generalistas, esto es que asimilan de manera equitativa las distintas fuentes de recursos, o como consumidores de segundo orden, con predominio de la fracción aportada por otros consumidores como los insectos. Esta tesis representa el primer estudio, conocido por la autora, que relaciona la dinámica de almacenamiento de reservas, con los recursos utilizados por la especie A. pisonii, mediante el uso combinado de los isótopos estables y los análisis de contenido estomacal. Estos resultados contribuyen un poco más al entendimiento de la relación manglar ↔ cangrejo y amplia el conocimiento sobre la ecología de esta especie en los manglares americanos.



### Mes

7

### Año

2010

### Universidad

Instituto Venezolano de Investifaciones Científicas

### Departamento

Ecología

### Título obtenido

Doctorado

### Tutor

Jesús Eloy Conde

### ORCID del Tutor

_No response_

### Tutor adicional

_No response_

### ORCID del segundo Tutor

_No response_

### Palabras clave

cangrejo de mangle, dieta, gradiente de vegetacion, isótopos estables

### Licencia

CC BY

### Confirmación de documentos

- [x] Confirmo que adjuntaré los documentos requeridos después de enviar este formulario
