name: Process Thesis Abstracts

on:
  push:
    branches:
      - main
    paths:
      - '_accepted/*.qmd'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Required to access HEAD^

      - name: Find changed .qmd files
        id: changed-files
        run: |
          # Safely get changed files (works for initial commit too)
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            FILES=$(git diff --name-only HEAD^ HEAD -- '_accepted/' | grep '\.qmd$')
          else
            FILES=$(git ls-files -- '_accepted/' | grep '\.qmd$')
          fi
          echo "files=$(echo "$FILES" | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Process abstracts
        run: |
          # Venezuelan university codes
          declare -A UNIVERSITY_MAP=(
            ["Universidad Simón Bolívar"]="usb"
            ["Universidad Central de Venezuela"]="ucv"
            ["Universidad de Los Andes"]="ula"
            ["Universidad de Oriente"]="udo"
            ["Universidad del Zulia"]="luz"
            ["Universidad de Carabobo"]="uc"
            ["Universidad Centroccidental Lisandro Alvarado"]="ucla"
            ["*"]="other"
          )

          for FILE in ${{ steps.changed-files.outputs.files }}; do
            echo "Processing: $FILE"

            # Extract metadata
            TITLE=$(grep -m1 '^title:' "$FILE" | sed 's/^title:[[:space:]]*//;s/"//g')
            AUTHOR=$(grep -m1 '^author:' "$FILE" | sed 's/^author:[[:space:]]*//;s/"//g')
            YEAR=$(grep -m1 '^year:' "$FILE" | sed 's/^year:[[:space:]]*//;s/"//g' || date +"%Y")
            UNIVERSITY=$(grep -A1 -i '^###.*Universidad' "$FILE" | tail -1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

            # Clean last name (last word of author field)
            LAST_NAME=$(echo "$AUTHOR" | awk '{print $NF}' | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]')
            UNIVERSITY=$(grep -A1 -i '^###.*Universidad' "$FILE" | tail -1 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [[ -z "$UNIVERSITY" || -z "${UNIVERSITY_MAP[$UNIVERSITY]+_}" ]]; then SHORT_UNIV="other"
            else
            SHORT_UNIV="${UNIVERSITY_MAP[$UNIVERSITY]}"
            fi

            # Create target directory and file
            TARGET_DIR="tesis/$SHORT_UNIV"
            mkdir -p "$TARGET_DIR"
            NEW_FILENAME="${YEAR}_${LAST_NAME}.qmd"

            # Build new YAML front matter
            {
              echo "---"
              echo "title: \"$TITLE\""
              echo "author: \"$AUTHOR\""
              echo "year: \"$YEAR\""
              echo "university: \"$UNIVERSITY\""
              echo "abstract: |"
              sed -n '/^## Abstract/,/^##/{/^##/!p}' "$FILE" | sed 's/^/  /'
              echo "---"
              sed '1,/^---/d' "$FILE" | sed '/^---/q' | sed '1d'
            } > "$TARGET_DIR/$NEW_FILENAME"

            echo "Saved to: $TARGET_DIR/$NEW_FILENAME"
          done

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tesis/
          git commit -m "Processed abstracts: year_lastname format"
          git push
