name: Process Form to Markdown

on:
  issues:
    types: [labeled]

jobs:
  convert-to-markdown:
    if: contains(github.event.issue.labels.*.name, 'approved')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Parse form data and create markdown
      env:
        ISSUE_BODY: ${{ github.event.issue.body }}
      run: |
        # Extract specific field (example: "Title: My Title")
        FILENAME_FIELD=$(echo "$ISSUE_BODY" | grep -oP 'Title:\s*\K.*' | head -1)
        
        # Clean the filename (remove special chars, replace spaces)
        CLEAN_FILENAME=$(echo "$FILENAME_FIELD" | \
          tr ' ' '-' | \
          tr -cd '[:alnum:]-' | \
          tr '[:upper:]' '[:lower:]')
        
        # Create markdown file path
        MD_FILE="_accepted/${CLEAN_FILENAME}.md"
        
        # Create the markdown content
        echo "---" > "$MD_FILE"
        echo "title: \"$FILENAME_FIELD\"" >> "$MD_FILE"
        echo "date: $(date +"%Y-%m-%d")" >> "$MD_FILE"
        echo "---" >> "$MD_FILE"
        echo "" >> "$MD_FILE"
        echo "$ISSUE_BODY" >> "$MD_FILE"
        
    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Add new content from approved issue #${{ github.event.issue.number }}"
        git push
